#backend/auth.py
"""
Supabase JWT authentication for FastAPI.

Purpose
-------
The frontend authenticates users through Supabase Auth and receives a JWT.
Every protected backend endpoint validates that JWT and extracts the
authenticated user information.

Flow
----
Frontend Login
    ↓
Supabase Auth
    ↓
JWT Access Token
    ↓
Authorization: Bearer <token>
    ↓
FastAPI (this file)
    ↓
CurrentUser(id, email)

Usage
-----
from backend.auth import AuthDep

@router.get("/projects")
def list_projects(current_user: AuthDep):
    return {"user_id": current_user.id}

Environment Variables
---------------------
SUPABASE_JWT_SECRET

This secret is used to verify JWT signatures generated by Supabase.

Dashboard:
Supabase → Project Settings → JWT Keys → Legacy JWT Secret
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Annotated

from fastapi import Depends, HTTPException, status
from fastapi.security import HTTPAuthorizationCredentials, HTTPBearer
from jose import ExpiredSignatureError, JWTError, jwt

from backend.config import settings

# ---------------------------------------------------------------------------
# Startup-time guard — fail loudly if the secret is missing.
# ---------------------------------------------------------------------------
# Secret used to verify Supabase-issued JWTs.
# Loaded from backend/config.py -> Settings.
# Application startup should fail immediately if this is missing.
_JWT_SECRET: str = settings.supabase_jwt_secret

if not _JWT_SECRET:
    raise RuntimeError(
        "SUPABASE_JWT_SECRET is not set.\n"
        "Find it in: Supabase Dashboard → Settings → API → JWT Settings → JWT Secret"
    )

_ALGORITHM = "HS256"

# auto_error=False so we return a clean 401 instead of FastAPI's default 403.
_bearer = HTTPBearer(auto_error=False)


# ---------------------------------------------------------------------------
# Return type
# ---------------------------------------------------------------------------
@dataclass(frozen=True)
class CurrentUser:
    id: str     # Supabase user UUID (JWT `sub` claim)
    email: str  # User email         (JWT `email` claim)


# ---------------------------------------------------------------------------
# Dependency
# ---------------------------------------------------------------------------
"""
Validate the Supabase access token and return the authenticated user.

Raises:
    HTTPException(401): If the token is missing, invalid, or expired.
"""
def get_current_user(
    credentials: Annotated[HTTPAuthorizationCredentials | None, Depends(_bearer)],
) -> CurrentUser:
    """
    Validates the Supabase JWT from the Authorization header.
    Raises HTTP 401 for: missing token, bad signature, expired token.
    """
    _401 = HTTPException(
        status_code=status.HTTP_401_UNAUTHORIZED,
        detail="Invalid or missing authentication token.",
        headers={"WWW-Authenticate": "Bearer"},
    )

    if credentials is None:
        raise _401

    try:
        payload = jwt.decode(
            credentials.credentials,
            _JWT_SECRET,
            algorithms=[_ALGORITHM],
            options={"verify_aud": False},  # Supabase sets aud="authenticated"
        )
    except ExpiredSignatureError:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Token has expired.",
            headers={"WWW-Authenticate": "Bearer"},
        )
    except JWTError:
        raise _401

    user_id: str | None = payload.get("sub")
    email: str | None   = payload.get("email")

    if not user_id or not email:
        raise _401

    return CurrentUser(id=user_id, email=email)


# Convenience alias — keeps route signatures to one import:
#   current_user: AuthDep
# Convenience dependency alias for authenticated routes.
AuthDep = Annotated[CurrentUser, Depends(get_current_user)]
